In [1]:
!git clone https://github.com/MishaelTech/series_analyzing_system.git

fatal: destination path 'series_analyzing_system' already exists and is not an empty directory.

In [2]:
!cd series_analyzing_system && git pull origin main

From https://github.com/MishaelTech/series_analyzing_system
 * branch            main       -> FETCH_HEAD
Already up to date.

In [3]:
!cd series_analyzing_system && pip install -r requirements.txt

Collecting git+https://github.com/huggingface/peft.git (from -r requirements.txt (line 14))
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-req-build-xua75q2z
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-xua75q2z
  Resolved https://github.com/huggingface/peft.git to commit 28a5ba1127cb4a72bbd322bf988da8ee5e784a87
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scrapy==2.11.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: beautifulsoup4==4.12.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (4.12.3)
Requirement already satisfied: transformers==4.44.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (4.44.0)
Requirement already satisfied: huggingface_hub==0.24.5 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (0.24.5)
Requirement already satisfied: nltk==3.8.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (3.8.1)
Requirement already satisfied: gradio==3.48.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (3.48.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (2.5.0+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.26.4)
Requirement already satisfied: pyvis==0.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 10)) (0.3.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 11)) (3.0.2)
Requirement already satisfied: evaluate==0.4.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (0.4.3)
Requirement already satisfied: python-dotenv==1.0.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (1.0.1)
Requirement already satisfied: trl==0.9.6 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (0.9.6)
Requirement already satisfied: bitsandbytes==0.43.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 16)) (0.43.3)
Requirement already satisfied: Twisted>=18.9.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (24.7.0)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (43.0.3)
Requirement already satisfied: cssselect>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: itemloaders>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: parsel>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (1.9.1)
Requirement already satisfied: pyOpenSSL>=21.0.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (24.2.1)
Requirement already satisfied: queuelib>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (1.7.0)
Requirement already satisfied: service-identity>=18.1.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (24.2.0)
Requirement already satisfied: w3lib>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (2.2.1)
Requirement already satisfied: zope.interface>=5.1.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (7.1.1)
Requirement already satisfied: protego>=0.1.15 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: itemadapter>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (75.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (24.1)
Requirement already satisfied: tldextract in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (5.1.2)
Requirement already satisfied: lxml>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (4.9.4)
Requirement already satisfied: defusedxml>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: PyDispatcher>=2.0.5 in /usr/local/lib/python3.10/dist-packages (from scrapy==2.11.2->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4==4.12.3->-r requirements.txt (line 2)) (2.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (3.16.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.44.0->-r requirements.txt (line 3)) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub==0.24.5->-r requirements.txt (line 4)) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub==0.24.5->-r requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1->-r requirements.txt (line 5)) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk==3.8.1->-r requirements.txt (line 5)) (1.4.2)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (4.2.2)
Requirement already satisfied: fastapi in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.115.3)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.4.0)
Requirement already satisfied: gradio-client==0.6.1 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.27.2)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (6.4.5)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (3.1.4)
Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (2.1.5)
Requirement already satisfied: matplotlib~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (3.7.1)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (3.10.10)
Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (10.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (2.9.2)
Requirement already satisfied: pydub in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.25.1)
Requirement already satisfied: python-multipart in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.0.12)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (2.10.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (0.32.0)
Requirement already satisfied: websockets<12.0,>=10.0 in /usr/local/lib/python3.10/dist-packages (from gradio==3.48.0->-r requirements.txt (line 6)) (11.0.3)
Requirement already satisfied: ipython>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from pyvis==0.3.2->-r requirements.txt (line 10)) (7.34.0)
Requirement already satisfied: jsonpickle>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from pyvis==0.3.2->-r requirements.txt (line 10)) (3.3.0)
Requirement already satisfied: networkx>=1.11 in /usr/local/lib/python3.10/dist-packages (from pyvis==0.3.2->-r requirements.txt (line 10)) (3.4.2)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3->-r requirements.txt (line 12)) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3->-r requirements.txt (line 12)) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate==0.4.3->-r requirements.txt (line 12)) (0.70.16)
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (from trl==0.9.6->-r requirements.txt (line 15)) (0.34.2)
Requirement already satisfied: tyro>=0.5.11 in /usr/local/lib/python3.10/dist-packages (from trl==0.9.6->-r requirements.txt (line 15)) (0.8.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 7)) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 7)) (2024.2)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 8)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch->-r requirements.txt (line 8)) (1.3.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 11)) (16.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 11)) (3.10.10)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from peft==0.13.3.dev0->-r requirements.txt (line 14)) (5.9.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.48.0->-r requirements.txt (line 6)) (0.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.48.0->-r requirements.txt (line 6)) (4.23.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio==3.48.0->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->scrapy==2.11.2->-r requirements.txt (line 1)) (1.17.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (1.16.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 11)) (4.0.3)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (0.19.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.3.0->pyvis==0.3.2->-r requirements.txt (line 10)) (4.9.0)
Requirement already satisfied: jmespath>=0.9.5 in /usr/local/lib/python3.10/dist-packages (from itemloaders>=1.0.1->scrapy==2.11.2->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.48.0->-r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.48.0->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.48.0->-r requirements.txt (line 6)) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.48.0->-r requirements.txt (line 6)) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio==3.48.0->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.48.0->-r requirements.txt (line 6)) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4->gradio==3.48.0->-r requirements.txt (line 6)) (2.23.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.44.0->-r requirements.txt (line 3)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.44.0->-r requirements.txt (line 3)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.44.0->-r requirements.txt (line 3)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.44.0->-r requirements.txt (line 3)) (2024.8.30)
Requirement already satisfied: pyasn1 in /usr/local/lib/python3.10/dist-packages (from service-identity>=18.1.0->scrapy==2.11.2->-r requirements.txt (line 1)) (0.6.1)
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python3.10/dist-packages (from service-identity>=18.1.0->scrapy==2.11.2->-r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: automat>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from Twisted>=18.9.0->scrapy==2.11.2->-r requirements.txt (line 1)) (24.8.1)
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python3.10/dist-packages (from Twisted>=18.9.0->scrapy==2.11.2->-r requirements.txt (line 1)) (23.10.4)
Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python3.10/dist-packages (from Twisted>=18.9.0->scrapy==2.11.2->-r requirements.txt (line 1)) (21.0.0)
Requirement already satisfied: incremental>=24.7.0 in /usr/local/lib/python3.10/dist-packages (from Twisted>=18.9.0->scrapy==2.11.2->-r requirements.txt (line 1)) (24.7.2)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.10/dist-packages (from tyro>=0.5.11->trl==0.9.6->-r requirements.txt (line 15)) (0.16)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.10/dist-packages (from tyro>=0.5.11->trl==0.9.6->-r requirements.txt (line 15)) (13.9.3)
Requirement already satisfied: shtab>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from tyro>=0.5.11->trl==0.9.6->-r requirements.txt (line 15)) (1.7.1)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn>=0.14.0->gradio==3.48.0->-r requirements.txt (line 6)) (0.14.0)
Requirement already satisfied: starlette<0.42.0,>=0.40.0 in /usr/local/lib/python3.10/dist-packages (from fastapi->gradio==3.48.0->-r requirements.txt (line 6)) (0.41.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.48.0->-r requirements.txt (line 6)) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.48.0->-r requirements.txt (line 6)) (1.0.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->gradio==3.48.0->-r requirements.txt (line 6)) (1.3.1)

In [4]:
!pip install pyngrok streamlit

Collecting pyngrok
  Downloading pyngrok-7.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting streamlit
  Downloading streamlit-1.39.0-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.10/dist-packages (from pyngrok) (6.0.2)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.9.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.12.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.43)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)
Collecting watchdog<6,>=2.1.5 (from streamlit)
  Downloading watchdog-5.0.3-py3-none-manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)
Downloading pyngrok-7.2.0-py3-none-any.whl (22 kB)
Downloading streamlit-1.39.0-py2.py3-none-any.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 69.4 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 74.6 MB/s eta 0:00:00
Downloading watchdog-5.0.3-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 7.0 MB/s eta 0:00:00
Installing collected packages: watchdog, pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.1 pyngrok-7.2.0 streamlit-1.39.0 watchdog-5.0.3

In [5]:
from pyngrok import ngrok

# Start a ngrok tunnel to the streamlit app
ngrok.set_auth_token("2n43ceCJmLANUY539SUTSFa9vFX_4q5A4gskCusEmbkDPAWkp")  # Set your ngrok auth token here if needed
# Modify the connect method to use config with addr for specifying the port
public_url = ngrok.connect(addr="8501", bind_tls=True)
# bind_tls=True is necessary for streamlit which defaults to https
print(f"Public URL: {public_url}")

# Run the streamlit app
!cd series_analyzing_system && streamlit run streamlit_app.py

Public URL: NgrokTunnel: "https://4064-34-127-62-206.ngrok-free.app" -> "http://localhost:8501"

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.127.62.206:8501

  Stopping...
Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/cli.py", line 238, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/cli.py", line 274, in _main_run
    bootstrap.run(file, is_hello, args, flag_options)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/bootstrap.py", line 326, in run
    asyncio.run(run_server())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/bootstrap.py", line 44, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/server/server.py", line 416, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.10/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.10/dist-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/bootstrap.py", line 44, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.10/dist-packages/streamlit/web/server/server.py", line 416, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.10/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/termui.py", line 634, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.10/dist-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

In [ ]:
!cd series_analyzing_system && python gradio_app.py

# Import Libraries

In [4]:
import pandas as pd
import re
from datasets import Dataset

# Load the Dataset (Transcript) .csv

In [5]:
data_path = 'series_analyzing_system/data/naruto.csv'
naruto_transcript_df = pd.read_csv(data_path)

In [6]:
naruto_transcript_df.head()

      name                                               line
0   Naruto   (Laughing) Give it up. (Shows the stone faces...
1  Hiruzen   (Turns away from his writing) I hope you’re n...
2    Ninja                                       Naseer Sabah
3    Ninja                        is the best person on earth
4   Naruto                                               muah

In [7]:
# Remove the character in braket or action from transcript using re
def remove_paranthesis(text):
    result = re.sub(r'\(.*?\)', '', text)

    return result

In [8]:
naruto_transcript_df['line'] = naruto_transcript_df['line'].apply(remove_paranthesis)

In [9]:
naruto_transcript_df.head()

      name                                               line
0   Naruto    Give it up.  You’re just bent, because you d...
1  Hiruzen    I hope you’re not bothering me with some tri...
2    Ninja                                       Naseer Sabah
3    Ninja                        is the best person on earth
4   Naruto                                               muah

In [10]:
# Get the response and make sure its not short
naruto_transcript_df["number_of_words"] = naruto_transcript_df["line"].str.strip().str.split("")
# Count it
naruto_transcript_df["number_of_words"] = naruto_transcript_df["number_of_words"].apply(lambda x: len(x))

In [11]:
naruto_transcript_df.head()

      name                                               line  number_of_words
0   Naruto    Give it up.  You’re just bent, because you d...              131
1  Hiruzen    I hope you’re not bothering me with some tri...               86
2    Ninja                                       Naseer Sabah               14
3    Ninja                        is the best person on earth               29
4   Naruto                                               muah                6

In [12]:
# Naruto respond flag, so anything that has naruto and the word is greater than 5
naruto_transcript_df['naruto_respond_flag'] = 0
naruto_transcript_df.loc[(naruto_transcript_df['name'] == 'Naruto')&(naruto_transcript_df["number_of_words"]>5), "naruto_respond_flag"] = 1

In [13]:
naruto_transcript_df

,name,line,number_of_words,naruto_respond_flag
0,Naruto,"Give it up. You’re just bent, because you d...",131,1
1,Hiruzen,I hope you’re not bothering me with some tri...,86,0
2,Ninja,Naseer Sabah,14,0
3,Ninja,is the best person on earth,29,0
4,Naruto,muah,6,1
...,...,...,...,...
158,Iruka,Congratulations. You graduate. Naruto’s stand...,177,0
159,Iruka,Huh?,6,0
160,Naruto,Iruka Sensei!,15,1
161,Iruka,Ah! That hurts!,17,0
162,Iruka,Naruto. This is only the beginning. The road...,191,0

In [14]:
# Picking the indexes and Excluding the first row because its just intializing coversation
indexes_to_take = list(naruto_transcript_df[(naruto_transcript_df['naruto_respond_flag'] == 1)& (naruto_transcript_df.index>0)].index)

In [15]:
indexes_to_take[:3]

[4, 6, 20]

In [16]:
# Create the prompt we will feed through the chatbot so it can act as naruto, and give it the statement set to naruto and the response so it can imitate it

system_prompt = """" Your are naruto from the anime "Naruto". Your responses should reflect his personalities and speech patterns \n"""
prompts=[]
for ind in indexes_to_take:
    prompt = system_prompt

    # What was said
    prompt += naruto_transcript_df.iloc[ind-1]["line"] + "\n"
    # Response
    prompt += naruto_transcript_df.iloc[ind]["line"]
    prompts.append(prompt)

In [17]:
print(prompts[5])

" Your are naruto from the anime "Naruto". Your responses should reflect his personalities and speech patterns
  Cut the stupid tricks! This is your last warning!
 This sucks. Loser.

In [18]:
# Puttint the prompts in pd df
df = pd.DataFrame({"prompt": prompts})
df.head()

                                              prompt
0  " Your are naruto from the anime "Naruto". You...
1  " Your are naruto from the anime "Naruto". You...
2  " Your are naruto from the anime "Naruto". You...
3  " Your are naruto from the anime "Naruto". You...
4  " Your are naruto from the anime "Naruto". You...

In [19]:
# Convert to huggingface dataset
dataset = Dataset.from_pandas(df)